version: "3.9"
services:

  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/${NAME_SERVICE}
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${NAME_SERVICE}
      MYSQL_PASSWORD: ${NAME_SERVICE}
      MYSQL_ROOT_PASSWORD: ${NAME_SERVICE}
      MYSQL_DATABASE: ${NAME_SERVICE}
      MYSQL_CHARSET: utf8
      MYSQL_PORT: 3306
      APPLICATION_ENVIRONMENT: development
      APPLICATION_DEBUG: 1
    volumes:
      - ./:/${NAME_SERVICE}
    depends_on:
      - mysql

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    environment:
     MYSQL_HOST: mysql
     MYSQL_USER: ${NAME_SERVICE}
     MYSQL_PASSWORD: ${NAME_SERVICE}
     MYSQL_ROOT_PASSWORD: ${NAME_SERVICE}
     MYSQL_DATABASE: ${NAME_SERVICE}
     MYSQL_CHARSET: utf8
     MYSQL_PORT: 3306
     APPLICATION_ENVIRONMENT: development
     APPLICATION_DEBUG: 1
    volumes:
      - ./:/${NAME_SERVICE}

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_USER: ${NAME_SERVICE}
      MYSQL_PASSWORD: ${NAME_SERVICE}
      MYSQL_ROOT_PASSWORD: ${NAME_SERVICE}
      MYSQL_DATABASE: ${NAME_SERVICE}
    volumes:
      - mysql:/var/lib/mysql
      - ./:/${NAME_SERVICE}
    ports:
      - "3306:3306"

  node-cli:
    build:
      context: docker
      dockerfile: node/Dockerfile
    volumes:
      - ./:/${NAME_SERVICE}

volumes:
  mysql:
