import style from './index.scss';
import { Montserrat } from 'next/font/google'
import {Header} from "@/components/Header/Header";

import dynamic from 'next/dynamic';

const DynamicBootstrap = dynamic(
  () => require('bootstrap/dist/js/bootstrap.min.js'),
  { ssr: false }
);

const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Service',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={font.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
