export const metadata = {
    title: 'fghfhfghfg',
    description: 'Generated by create next app',
}
export default function About() {
    return (<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi atque ex expedita laudantium numquam porro provident sequi, voluptatum! Ab amet, architecto consequatur dolorum eaque modi nostrum quas sequi! Quod, soluta!</div>)
}
